sudo: false
language: rust
cache: cargo
rust:
  - nightly
  - nightly-2018-12-04
  - beta
  - stable
matrix:
  allow_failures:
    - rust: nightly
script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == nightly* ]]; then
        cargo clippy
        cargo build --verbose
    else
        cargo build --verbose
    fi
addons:
  apt:
    sources:
        - kalakris-cmake
    packages:
        - cmake
