sudo: false
language: rust
cache: cargo
rust:
  - nightly
  - nightly-2016-10-18
  - beta
  - stable
matrix:
  allow_failures:
    - rust: nightly
script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == nightly* ]]; then
        cargo build --verbose --features="clippy"
    else
        cargo build --verbose 
    fi
addons:
  apt:
    sources:
        - kalakris-cmake
    packages:
        - cmake
